### ISSUE TITLE
输入案例的内容后报错「image not found」

### ISSUE THREAD

**Issue by zx490336534** [nanoric/c2py#1]
```shell
zhongxindeMacBook-Pro:ctp zhongxin$ uname -a
Darwin zhongxindeMacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

```shell
zhongxindeMacBook-Pro:ctp zhongxin$ c2py generate vnctp                                     \
>     ThostFtdcMdApi.h                                    \
>     ThostFtdcTraderApi.h                                \
>     ThostFtdcUserApiDataType.h                          \
>     ThostFtdcUserApiStruct.h                            \
>     -I                          vnctp/include/          \
>     --no-callback-pattern       ".*Api::.*"             \
>     --string-encoding-windows   .936                    \
>     --string-encoding-linux     zh_CN.GB18030           \
>                                                         \
>     --copy-c2py-includes   vnctp/include/               \
>     --output-dir                vnctp/generated_files/  \
>     --clear-output-dir                                  \
>                                                         \
>     --generate-setup            .                       \
>     --setup-lib-dir             vnctp/libs/             \
>     --setup-lib                 thostmduserapi          \
>     --setup-lib                 thosttraderapi
c2py 0.5.4
parsing ...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/c2py-0.5.4-py3.7.egg/c2py/clang/cindex.py", line 4170, in get_cindex_library
    library = cdll.LoadLibrary(self.get_filename())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/c2py-0.5.4-py3.7.egg/c2py/core/../clang/libclang.dylib, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/c2py", line 11, in <module>
    load_entry_point('c2py==0.5.4', 'console_scripts', 'c2py')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/c2py-0.5.4-py3.7.egg/c2py/cli.py", line 214, in generate
    parser_result = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/c2py-0.5.4-py3.7.egg/c2py/core/cxxparser.py", line 177, in parse
    idx = Index.create()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/c2py-0.5.4-py3.7.egg/c2py/clang/cindex.py", line 2688, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/c2py-0.5.4-py3.7.egg/c2py/clang/cindex.py", line 209, in __get__
    value = self.wrapped(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/c2py-0.5.4-py3.7.egg/c2py/clang/cindex.py", line 4144, in lib
    lib = self.get_cindex_library()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/c2py-0.5.4-py3.7.egg/c2py/clang/cindex.py", line 4175, in get_cindex_library
    raise LibclangError(msg)
c2py.clang.cindex.LibclangError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/c2py-0.5.4-py3.7.egg/c2py/core/../clang/libclang.dylib, 6): image not found. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
```

**Comment by nanoric** [comment]
我这里没有内置Linux下的libclang.so。你可以暂时考虑自己复制一个。
等下我会拷进来。

**Comment by zx490336534** [comment]
在win32上出现
```shell
---------------------------
python3.exe - 损坏的图像
---------------------------
E:\python3\lib\site-packages\c2py-0.5.4-py3.7.egg\c2py\clang\libclang.dll 没有被指定在 Windows 上运行，或者它包含错误。请尝试使用原始安装媒体重新安装程序，或联系您的系统管理员或软件供应商以获取支持。 
---------------------------
确定   
---------------------------
```
安装的时候是不是需要自动注册dll？

**Comment by zx490336534** [comment]
win64：
```shell
F:\c2py\tests\generate\ctp>c2py generate vnctp ThostFtdcMdApi.h ThostFtdcTraderApi.h ThostFtdcUserApiDataType.h ThostFtdcUserApiStruct.h -I vnctp/incl
ude/ --no-callback-pattern ".*Api::.*" --string-encoding-windows .936 --string-encoding-linux zh_CN.GB18030 --copy-c2py-includes   vnctp/include/ --ou
tput-dir vnctp/generated_files/  --clear-output-dir --generate-setup . --setup-lib-dir vnctp/libs/ --setup-lib thostmduserapi --setup-lib thosttradera
pi
c2py 0.5.4
parsing ...
Traceback (most recent call last):
  File "E:\python3\lib\site-packages\c2py\clang\cindex.py", line 4170, in get_cindex_library
    library = cdll.LoadLibrary(self.get_filename())
  File "E:\python3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "E:\python3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python3\Scripts\c2py-script.py", line 11, in <module>
    load_entry_point('c2py==0.5.4', 'console_scripts', 'c2py')()
  File "E:\python3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "E:\python3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "E:\python3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\python3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\python3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "E:\python3\lib\site-packages\c2py\cli.py", line 214, in generate
    parser_result = parser.parse()
  File "E:\python3\lib\site-packages\c2py\core\cxxparser.py", line 177, in parse
    idx = Index.create()
  File "E:\python3\lib\site-packages\c2py\clang\cindex.py", line 2688, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "E:\python3\lib\site-packages\c2py\clang\cindex.py", line 209, in __get__
    value = self.wrapped(instance)
  File "E:\python3\lib\site-packages\c2py\clang\cindex.py", line 4144, in lib
    lib = self.get_cindex_library()
  File "E:\python3\lib\site-packages\c2py\clang\cindex.py", line 4175, in get_cindex_library
    raise LibclangError(msg)
c2py.clang.cindex.LibclangError: [WinError 193] %1 不是有效的 Win32 应用程序。. To provide a path to libclang use Config.set_library_path() or Config.
set_library_file().

F:\c2py\tests\generate\ctp>
```
查看具体报错文件
```python
def get_cindex_library(self):
        try:
            library = cdll.LoadLibrary(self.get_filename())
        except OSError as e:
            msg = str(e) + f'[{self.get_filename()}]' +". To provide a path to libclang use " \
                           "Config.set_library_path() or " \
                           "Config.set_library_file()."
            raise LibclangError(msg)

        return library
```
```shell
c2py.clang.cindex.LibclangError: [WinError 193] %1 不是有效的 Win32 应用程序。[E:\python3\lib\site-packages\c2py\core\../clang/libclang.dll]. To provi
de a path to libclang use Config.set_library_path() or Config.set_library_file().
```

**Comment by nanoric** [comment]
Windows下的话，请尝试安装VC Redist 2015，对应的下载地址：
https://support.microsoft.com/en-ph/help/2977003/the-latest-supported-visual-c-downloads
