### ISSUE TITLE
.h文件的编码问题

### ISSUE THREAD

**Issue by zx490336534** [nanoric/c2py#2]
`c2py.clang.cindex.c_interop_string#value`
中固定使用utf8编码进行转码，部分.h文件注释格式为gbk或者其他，会导致运行报错

**Comment by nanoric** [comment]
谢谢你的反馈。
问题已经修复。
现在可以使用-e或者--encoding指定输入文件的编码：
-e gbk

**Comment by zx490336534** [comment]
在`c2py.core.cxxparser.CxxFileParser#__init__`里面也可能出现问题
```python
$ /d/SDK/change.sh
c2py 0.5.4
parsing ...
imos64/include/sdk_func.h
'gbk' codec can't decode byte 0xa3 in position 74833: illegal multibyte sequence
Traceback (most recent call last):
  File "E:\python37\lib\site-packages\c2py-0.5.4-py3.7.egg\c2py\core\cxxparser.py", line 720, in __init__
    data = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa3 in position 74833: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python37\Scripts\c2py-script.py", line 11, in <module>
    load_entry_point('c2py==0.5.4', 'console_scripts', 'c2py')()
  File "E:\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "E:\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "E:\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "E:\python37\lib\site-packages\c2py-0.5.4-py3.7.egg\c2py\cli.py", line 213, in generate
    parser = CxxFileParser(files=files, encoding=encoding, include_paths=include_dirs)
  File "E:\python37\lib\site-packages\c2py-0.5.4-py3.7.egg\c2py\core\cxxparser.py", line 725, in __init__
    raise Exception
Exception

```
是不是加上`errors='ignore'`比较合适
```python
with open(real_path, 'rt', encoding=encoding, errors='ignore') as f:
```

**Comment by nanoric** [comment]
对的，加上去比价好。能麻烦你提交一个PR吗？
